
# This is an Alembic migration script template.
# It will be rendered into a new migration file inside migrations/versions/.

"""init

Revision ID: 06f85f41ba46
Revises: 
Create Date: 2025-11-01 16:20:37.877446
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '06f85f41ba46'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('ein', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('legal_representative', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('instagram_user', sa.String(length=255), nullable=True),
    sa.Column('facebook_page', sa.String(length=255), nullable=True),
    sa.Column('meta_bm_id', sa.String(length=255), nullable=True),
    sa.Column('meta_ads_account_id', sa.String(length=255), nullable=True),
    sa.Column('google_ads_id', sa.String(length=32), nullable=True),
    sa.Column('analytics', sa.Boolean(), nullable=True),
    sa.Column('tag_manager', sa.Boolean(), nullable=True),
    sa.Column('search_console', sa.Boolean(), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('hosting', sa.String(length=255), nullable=True),
    sa.Column('hosting_login', sa.String(length=255), nullable=True),
    sa.Column('hosting_password', sa.String(length=255), nullable=True),
    sa.Column('domain_registrar', sa.String(length=255), nullable=True),
    sa.Column('domain_login', sa.String(length=255), nullable=True),
    sa.Column('domain_password', sa.String(length=255), nullable=True),
    sa.Column('brand_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signer_name', sa.String(length=255), nullable=True),
    sa.Column('signer_email', sa.String(length=255), nullable=True),
    sa.Column('signer_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('signature_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('signer_name', sa.String(length=255), nullable=True),
    sa.Column('signer_email', sa.String(length=255), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signer_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('signature_path', sa.String(length=255), nullable=True),
    sa.Column('contract_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract')
    op.drop_table('access_request')
    op.drop_table('client')
    # ### end Alembic commands ###
