
# This is an Alembic migration script template.
# It will be rendered into a new migration file inside migrations/versions/.

"""asset public token + schedule fields

Revision ID: bcfcda7dcec5
Revises: fa22218c8148
Create Date: 2025-11-01 16:44:26.911884
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bcfcda7dcec5'
down_revision = 'fa22218c8148'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
