
# This is an Alembic migration script template.
# It will be rendered into a new migration file inside migrations/versions/.

"""add account_manager_email to client

Revision ID: cb2311aa65df
Revises: bcfcda7dcec5
Create Date: 2025-11-01 17:22:09.065003
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cb2311aa65df'
down_revision = 'bcfcda7dcec5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('account_manager_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'account_manager_email')
    # ### end Alembic commands ###
