
# This is an Alembic migration script template.
# It will be rendered into a new migration file inside migrations/versions/.

"""add asset table

Revision ID: f0c7b38a1502
Revises: cb2311aa65df
Create Date: 2025-11-02 01:56:42.447392
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f0c7b38a1502'
down_revision = 'cb2311aa65df'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
