
# This is an Alembic migration script template.
# It will be rendered into a new migration file inside migrations/versions/.

"""asset public token + schedule fields

Revision ID: fa22218c8148
Revises: 5f1971249f6f
Create Date: 2025-11-01 16:39:47.515787
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fa22218c8148'
down_revision = '5f1971249f6f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('public_token', sa.String(length=64), nullable=True))
    op.add_column('asset', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True))
    op.add_column('asset', sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('asset', sa.Column('client_comment', sa.Text(), nullable=True))
    op.create_index('idx_asset_client_status', 'asset', ['client_id', 'status'], unique=False)
    op.create_index(op.f('ix_asset_public_token'), 'asset', ['public_token'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_public_token'), table_name='asset')
    op.drop_index('idx_asset_client_status', table_name='asset')
    op.drop_column('asset', 'client_comment')
    op.drop_column('asset', 'posted_at')
    op.drop_column('asset', 'scheduled_for')
    op.drop_column('asset', 'public_token')
    # ### end Alembic commands ###
